# THIS FILE WAS AUTOGENERATED, DO NOT EDIT
abort 'Use the rake task or esr-gem-builder to build the gem' if $0 =~ /gem$/ && $*.first == 'build'
Gem::Specification.new do |s|
  s.name = "rtext"
  s.version = "0.9.2"
  s.authors = ["Martin Thiede"]
  s.homepage = "http://ruby-gen.org"
  s.summary = "Ruby Textual Modelling"
  s.description = "RText can be used to derive textual languages from an RGen metamodel with very little effort."
  s.licenses = nil
  s.bindir = "bin"
  s.executables = nil
  s.extra_rdoc_files = ["README.rdoc", "CHANGELOG", "MIT-LICENSE", "RText_Users_Guide", "RText_Protocol"]
  s.rdoc_options << "--main" << "README.rdoc" << "-x" << "test"
  s.files = ["Project.yaml"] + Dir.glob("lib/**/*.rb")
  s.add_dependency("rgen", "~> 0.8.0")
end
